AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PokemonApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Pokemon API Gateway
      Description: Integration with PokeAPI to get information about pokemons.
  
  PokemonLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PokemonApiLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
  
  PokemonLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
  
  PokemonApiLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt PokemonLambdaExecutionRole.Arn
      Runtime: nodejs18.x
      Code:
        S3Bucket: pokemon-lambda-code
        S3Key: pokemon_api/pokemon_get.zip
  
  PokemonGetResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PokemonApiGateway 
      ParentId: !GetAtt PokemonApiGateway.RootResourceId
      PathPart: pokemon
  
  PokemonGetMethod:
    Type: AWS::ApiGateway::Method
    DependsOn: PokemonApiUserPoolAuthorizer
    Properties:
      RestApiId: !Ref PokemonApiGateway
      ResourceId: !Ref PokemonGetResource
      HttpMethod: GET
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref PokemonApiUserPoolAuthorizer
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PokemonApiLambdaFunction.Arn}/invocations
      RequestParameters:
        method.request.querystring.name: true
  
  PokemonApiUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: PokemonApiUserPool
      Schema:
        - Name: email
          Required: true
          Mutable: false
      AutoVerifiedAttributes:
        - email
  
  PokemonApiUserPoolResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties: 
        Identifier: pokemon
        Name: Pokemon API
        UserPoolId: !Ref PokemonApiUserPool
        Scopes: 
            - ScopeName: "read"
              ScopeDescription: "read access"
  
  PokemonApiUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: PokemonApiUserPoolResourceServer
    Properties:
      ClientName: PokemonApiUserPoolClient
      GenerateSecret: true
      AllowedOAuthScopes:
        - pokemon/read
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthFlowsUserPoolClient: true
      UserPoolId: !Ref PokemonApiUserPool
  
  PokemonApiUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: "pokemon-api-auth"
      UserPoolId: !Ref PokemonApiUserPool
  
  PokemonApiUserPoolAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: PokemonApiUserPoolAuthorizer
      RestApiId: !Ref PokemonApiGateway
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      ProviderARNs:
        - !GetAtt PokemonApiUserPool.Arn
  
  PokemonApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - PokemonGetMethod
    Properties:
      RestApiId: !Ref PokemonApiGateway
      StageName: "api"
      Description: "Deployment for the Pokemon API Gateway"
  
  PokemonApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    DependsOn:
      - PokemonApiGatewayDeployment
      - PokemonApiGatewayLogGroup
    Properties:
      StageName: "api"
      Description: "Production Stage"
      RestApiId: !Ref PokemonApiGateway
      DeploymentId: !Ref PokemonApiGatewayDeployment
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: "INFO"
          DataTraceEnabled: true
          MetricsEnabled: true
      TracingEnabled: true
      Variables:
        lambdaFunctionName: !Ref PokemonApiLambdaFunction
      AccessLogSetting:
        DestinationArn: !GetAtt PokemonApiGatewayLogGroup.Arn
        Format: "{\"requestId\":\"$context.requestId\", \"ip\":\"$context.identity.sourceIp\", \"caller\":\"$context.identity.caller\", \"user\":\"$context.identity.user\", \"requestTime\":\"$context.requestTime\", \"httpMethod\":\"$context.httpMethod\", \"resourcePath\":\"$context.resourcePath\", \"status\":\"$context.status\", \"protocol\":\"$context.protocol\", \"responseLength\":\"$context.responseLength\"}"
  
  PokemonApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/apigateway/PokemonApiGatewayLogs"
      RetentionInDays: 14
Outputs:
  PokemonApiLambdaFunctionName:
    Description: "Name of the Pokemon API Lambda function"
    Value: !Ref PokemonApiLambdaFunction
  PokemonApiGateway:
    Description: "Pokemon Gateway name"
    Value: !Ref PokemonApiGateway