AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PokemonLambdaCode:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pokemon-lambda-code
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true