AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PokemonApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Pokemon API Gateway
      Description: Integration with PokeAPI to get informations about pokemons.
  PokemonApiLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs18.x
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: "Hello from Pokemon lambda" }),
            };
          };
  PokemonGetResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PokemonApiGateway 
      ParentId: !GetAtt PokemonApiGateway.RootResourceId
      PathPart: pokemon
  PokemonLambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pokemon-lambda-code-bucket
  PokemonGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PokemonApiGateway
      ResourceId: !Ref PokemonGetResource
      HttpMethod: GET
      AuthorizationType: NONE